apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: k8s-demo-cronjob
spec:
  schedule: "*/1 * * * *"   # 每隔1分钟执行一次
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: k8s-demo-cron-job
              image: k8s-backend-log
              imagePullPolicy: Never
              command:
                - "bin/sh"
                - "-c"
                - "for i in 9 8 7 6 5 4 3 2 1; do echo $i; done"
          restartPolicy: OnFailure