apiVersion: v1
kind: Pod
metadata:
  name: k8s-demo
  labels:     # 为 pod 打上 label  可以被service使用，查看ser.yml selector
    app: k8s-demo
spec:
  containers:
    - name: k8s-demo-pod
      image: k8s-backend
      imagePullPolicy: Never
      ports:
        - containerPort: 8080